cxx_binary(
  name = 'example',
  srcs = [
    'main.cpp',
  ],
  deps = [
    '//:boost-xpressive',
  ],
)

cxx_binary(
  name = 'numbers',
  srcs = [
    'numbers.cpp',
  ],
  deps = [
    '//:boost-xpressive',
  ],
)
